<?php
	echo $this->doctype();
	$this->title = "Chương trình trọng điểm";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách chương trình trọng điểm</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_chuong_trinh">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'chuong-trinh','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_hoithao" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th class="chu_de" style="width: 65%;">Tên</th>
			<th class="center">Ngày tạo</th>
			<th class="center">Trạng thái</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'chuong-trinh','action' => 'them'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $chuong_trinh) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$chuong_trinh->getIdentity(),null)?></td>
			<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'chuong-trinh','action' => 'sua','id' => $chuong_trinh->getIdentity()),null,true)?>" title="<?php echo $chuong_trinh->ten?>"><?php echo Khcn_Api::_()->subPhrase($chuong_trinh->ten, 200);?></a></td>
			<td class="center"><?php echo date('d-m-Y', strtotime($chuong_trinh->ngay_tao))?></td>
			<td class="center">
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'chuong-trinh','action' => 'cap-nhat-tt','id' => $chuong_trinh->getIdentity(),'status' => $chuong_trinh['trang_thai']))?>">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/trangthai_' . $chuong_trinh['trang_thai'] . '.png'?>"> </a>
			</td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'chuong-trinh','action' => 'sua','id' => $chuong_trinh->getIdentity()),null,true)?>" title="Sửa"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'chuong-trinh','action' => 'xoa','id' => $chuong_trinh->getIdentity()),null,true)?>" title="Xóa" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->