<?php
	echo $this->doctype();
	$this->title = "Qui định";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách qui định</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_qui_dinh">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'qui-dinh','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_quidinh" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th>Tên</th>
			<th class="center">Loại</th>
			<th class="center">Trạng thái</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'qui-dinh','action' => 'them'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $qui_dinh) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$qui_dinh['id'],null)?></td>
			<td class="ten"><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'qui-dinh','action' => 'sua','id' => $qui_dinh['id']),null,true)?>"><?php echo $qui_dinh['ten']?></a></td>
			<td class="center"><?php echo $this->loais[$qui_dinh['loai']]?></td>
			<td class="center">
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'qui-dinh','action' => 'cap-nhat-tt','id' => $qui_dinh['id'],'status' => $qui_dinh['trang_thai']))?>">
				<img src="<?php echo $this->baseUrl() . '/../application/templates/admin/images/icons/trangthai_' . $qui_dinh['trang_thai'] . '.png'?>"> </a>
			</td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'qui-dinh','action' => 'sua','id' => $qui_dinh['id']),null,true)?>" title="Edit"> 
				<img src="<?php echo $this->baseUrl() . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'qui-dinh','action' => 'xoa','id' => $qui_dinh['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $this->baseUrl() . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->