<?php
	echo $this->doctype();
	$this->title = "Liên kết";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<script>
	function thuoc_sgu(lien_ket_id){
		var element = document.getElementById('lien_ket_content_' + lien_ket_id);
		var checkbox = document.getElementById('lien_ket_' + lien_ket_id);
		var status = 0;
		
		if(checkbox.checked==true) status = 1;
		else status = 0;
		var content = element.innerHTML;
		element.innerHTML= "<img  src='<?php echo $this->baseUrl()?>/../application/modules/Default/externals/images/loading.gif'></img>";
		
		$.ajax({ 
			type: "POST", 
			url: "<?php echo $this->url(array('module' => 'admin','controller' => 'lien-ket','action' => 'thuoc-sgu'))?>", 
			data: {
				'format' : 'json',
				'lien_ket_id' : lien_ket_id,
				'status' : status
			},
			success: function(data){
				element.innerHTML = content;
				checkbox = document.getElementById('lien_ket_' + lien_ket_id);
				if( status == 1) checkbox.checked=true;
				else checkbox.checked=false;
			}
		});
    }
</script>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách liên kết</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_lien_ket">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'lien-ket','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_bieumau" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th>Tên</th>
			<th class="center">Url</th>
			<th class="center">Thuộc SGU</th>
			<th class="center">Thứ tự</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'lien-ket','action' => 'them'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $lien_ket) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$lien_ket['id'],null)?></td>
			<td class="ten"><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'lien-ket','action' => 'sua','id' => $lien_ket['id']),null,true)?>"><?php echo $lien_ket['ten']?></a></td>
			<td class="center"><?php echo $lien_ket['url']?></td>
			<td class="center">
				<div id='lien_ket_content_<?php echo $lien_ket->getIdentity(); ?>'>
					<?php if($lien_ket->is_sgu): ?>
						<input type="checkbox" id='lien_ket_<?php echo $lien_ket->getIdentity(); ?>'  onclick="thuoc_sgu(<?php echo $lien_ket->getIdentity(); ?>,this)" checked />
					<?php else: ?>
						<input type="checkbox" id='lien_ket_<?php echo $lien_ket->getIdentity(); ?>'  onclick="thuoc_sgu(<?php echo $lien_ket->getIdentity(); ?>,this)" />
					<?php endif; ?>
				</div>
			</td>
			<td class="center"><?php echo $lien_ket['order']?></td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'lien-ket','action' => 'sua','id' => $lien_ket['id']),null,true)?>" title="Edit"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'lien-ket','action' => 'xoa','id' => $lien_ket['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->