<div class="art-footer">
<div class="art-footer-t"></div>
<div class="art-footer-l"></div>
<div class="art-footer-b"></div>
<div class="art-footer-r"></div>
<div class="art-footer-body">
<div class="art-footer-text">

<div class="footer">
	<p>
		&copy;2012 Phòng Khoa học - Công nghệ - SGU. <br/>
		273 An Dương Vương , P.3 , Q.5 , TP.HCM.<br/>
		Design by Hung Nguyen - K08.
	</p>
</div>
</div>
<div class="cleared"></div>
</div>
</div>