<?php
	echo $this->doctype();
	$this->title = "Giảng viên";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<script>
	var currentOrder = '<?php echo $this->filterValues['order'] ?>';
    var currentOrderDirection = '<?php echo $this->filterValues['direction'] ?>';
    var changeOrder = function(order, default_direction)
    {
		// Just change direction
		if( order == currentOrder ) {
			$('#direction').val( currentOrderDirection == 'ASC' ? 'DESC' : 'ASC' );
		} else {
			$('#order').val(order);
			$('#direction').val(default_direction);
		}
		$('#f3').submit();
    }
</script>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách giảng viên chưa xác định đơn vị</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<?php echo $this->form;?>
<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div id="ds_gv">
<div class="clear"></div>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'giang-vien','action' => 'xoas'),null,true)?>" method="post" name="f2">
<table class="tbl_giangvien" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th class="center"><a href="javascript:void(0);" onclick="javascript:changeOrder('ho_ten', 'ASC');">Họ tên</a></th>
			<th class="center">Đơn vị</th>
			<th class="center">Chức vụ</th>
			<th class="center">Trạng thái</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>	
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $giang_vien) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$giang_vien['id'],null)?></td>
			<td class="center"><?php echo ($giang_vien['hoc_vi'] == '0' ? '' : $giang_vien['hoc_vi'] ) . '. ' . $giang_vien['ho'] . ' ' . $giang_vien['ten'];?></td>
			<td class="center"><?php echo $this->formSelect('don_vi',33,array('onchange' => 'changeDV(this,' . $giang_vien['id'] . ')'),$this->donVis) ;?></td>
			<td class="center"><?php echo $giang_vien['chuc_vu'];?></td>
			<td class="center">
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'giang-vien','action' => 'cap-nhat-tt','id' => $giang_vien['id'],'status' => $giang_vien['trang_thai']))?>">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/trangthai_' . $giang_vien['trang_thai'] . '.png'?>"> </a>
			</td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'giang-vien','action' => 'sua-gv-ngoai-sgu','id' => $giang_vien['id']),null,true)?>" title="Edit"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'giang-vien','action' => 'xoa','id' => $giang_vien['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<script type="text/javascript">
function changeDV(dk,ma)
{
	var ma_don_vi = dk.value;
	$.ajax({ type: "GET", 
	 url: "<?php echo $this->url(array('module' => 'admin','controller' => 'giang-vien','action' => 'cap-nhat-dv'))?>",
	 data: {'id' : ma,'ma_don_vi' : ma_don_vi},
	 success: function(data){
         if (data == "YES") {
	         alert('Thành công. Dữ liệu đã được cập nhật.');
			 location.reload();
         }else if(data == "NO"){
	         alert('Lỗi. Đã có lỗi trong quá trình xử lý, vui lòng kiểm tra lại.');
         }}
	});
}
</script>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->