<?php
	echo $this->doctype();
	$this->title = "Giảng viên";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box"><!-- Start Content Box -->

<div class="content-box-header">

<h3>Cập nhật giảng viên</h3>
</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1"><!-- This is the target div. id must match the href of this div's tab -->
<?php echo $this->form?>
<script type="text/javascript">
function inputNumber(e)
{
	var keynum;
	if(window.event) // IE
	{
	  keynum = e.keyCode;
	}
	else if(e.which) // Netscape/Firefox/Opera
	{
	  keynum = e.which;
	}
	if ( ((keynum > 45) && (keynum <58)) || (keynum == 8) || (keynum == 9) || (keynum == 190) || (keynum == 39)|| (keynum == 37) ) 	 			return true;
	else 
		return false;
}
</script>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->