<?php 
	$baseURL = $this->baseUrl();
?>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'de-tai','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<fieldset>
<table class="tbl_detai" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('check_all',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th>Mã</th>
			<th class="ten">Tên</th>
			<th class="center">Lĩnh vực</th>
			<th class="center">Tình trạng</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'de-tai','action' => 'them'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $de_tai) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$de_tai['id'],array('id' => 'ma[]'))?></td>
			<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'de-tai','action' => 'sua','id' => $de_tai['id']),null,true)?>"><?php echo $de_tai['ma']?></a></td>
			<td class="ten"><?php echo $de_tai['ten']?></td>
			<td class="center"><?php echo $de_tai['ten_linh_vuc'];?></td>
			<td class="center"><?php echo $this->formSelect('tinh_trang',$de_tai['tinh_trang'],array('id' => 'tinh_trang','onchange' => 'changeTT(this,' . $de_tai['id'] . ')'),Default_Model_Constraints::detai_tinhtrang()) ;?></td>			
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'de-tai','action' => 'sua','id' => $de_tai['id']),null,true)?>" title="Edit"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'de-tai','action' => 'xoa','id' => $de_tai['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
    </tbody>
</table>
</fieldset>
</form>
<script type="text/javascript">
	$(document).ready(function(){ // this line makes sure this code runs on page load
	    $('#check_all').click(function () {
	    	$(this).parents('fieldset').find(':checkbox').attr('checked', this.checked);
	    });
	});
</script>