<?php
	$this->title = "Lịch công tác";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box"><!-- Start Content Box -->

<div class="content-box-header">

<h3>Thêm hoạt động</h3>

<div class="clear"></div>
</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1"><!-- This is the target div. id must match the href of this div's tab -->
<div class="lich_cong_tac_info">
	<div class="title"><?php echo $this->translate('Lịch công tác: ')?></div>
	<div class="content"><?php echo 'Tuần ' . $this->lich_ct->tuan . ' - Tháng ' . $this->lich_ct->thang . ' ( ' . date('d/m/Y', strtotime($this->lich_ct->ngay_bat_dau)) . ' - ' . date('d/m/Y', strtotime($this->lich_ct->ngay_ket_thuc)) . ' )'?></div>
</div>
<?php echo $this->form?>
</div>
<script>
$(function() {
	$( "#ngay" ).datepicker({
		showOn: "button",
		changeMonth: true,
		buttonImage: "<?php echo $baseURL . '/images/calendar.gif'?>",
		buttonImageOnly: true,
		altFormat: 'yy-mm-dd',
		dateFormat: 'yy-mm-dd'
	});
});
</script>
<!-- End #tab1 -->
<!--<div class="tab-content" id="tab2"></div>-->
</div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->