<?php
	echo $this->doctype();
	$this->title = "Tin tức";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<script>
	var currentOrder = '<?php echo $this->filterValues['order'] ?>';
    var currentOrderDirection = '<?php echo $this->filterValues['direction'] ?>';
    var changeOrder = function(order, default_direction)
    {
		var direction = '';
		// Just change direction
		if( order == currentOrder ) {
			direction = currentOrderDirection == 'ASC' ? 'DESC' : 'ASC';
		} else {
			direction = default_direction;
		}
		window.location.href = '<?php echo $this->baseUrl()?>/admin/tin-tuc/index?order=' + order + '&direction=' + direction;
    }
	
	function update(type, tin_tuc_id){
		var element = document.getElementById('tin_tuc_content_' + type + '_' + tin_tuc_id);
		var checkbox = document.getElementById('tin_tuc_' + type + '_' + tin_tuc_id);
		var status = 0;
		
		if(checkbox.checked==true) status = 1;
		else status = 0;
		var content = element.innerHTML;
		element.innerHTML= "<img  src='<?php echo $this->baseUrl()?>/../application/modules/Default/externals/images/loading.gif'></img>";
		
		$.ajax({ 
			type: "POST", 
			url: "<?php echo $this->url(array('module' => 'admin','controller' => 'tin-tuc','action' => 'update'))?>", 
			data: {
				'format' : 'json',
				'tin_tuc_id' : tin_tuc_id,
				'type': type,
				'status' : status
			},
			success: function(data){
				element.innerHTML = content;
				checkbox = document.getElementById('tin_tuc_' + type + '_' + tin_tuc_id);
				if( status == 1) checkbox.checked=true;
				else checkbox.checked=false;
			}
		});
    }
</script>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách tin tức</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_tin_tuc">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'tin-tuc','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_tintuc" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th class="tieu_de" style="width: 50%">Tiêu đề</th>
			<th class="center">Ngày tạo</th>
			<th class="center">Trạng thái</th>
			<th class="center"><a href="javascript:void(0);" onclick="javascript:changeOrder('quan_trong', 'DESC');">Quan trọng</a></th>
			<th class="center"><a href="javascript:void(0);" onclick="javascript:changeOrder('noi_bat', 'DESC');">Nổi bật</a></th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'tin-tuc','action' => 'them'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $tin_tuc) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$tin_tuc['id'],null)?></td>
			<td class="tieu_de"><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'tin-tuc','action' => 'sua','id' => $tin_tuc['id']),null,true)?>"><?php echo $tin_tuc['tieu_de']?></a></td>			
			<td class="center"><?php echo date('d-m-Y',strtotime($tin_tuc['ngay_tao']))?></td>
			<td class="center">
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'tin-tuc','action' => 'cap-nhat-tt','id' => $tin_tuc['id'],'status' => $tin_tuc['trang_thai']))?>">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/trangthai_' . $tin_tuc['trang_thai'] . '.png'?>"> </a>
			</td>
			<td class="center">
				<div id='tin_tuc_content_quan_trong_<?php echo $tin_tuc->getIdentity(); ?>'>
					<?php if($tin_tuc->quan_trong): ?>
						<input type="checkbox" id='tin_tuc_quan_trong_<?php echo $tin_tuc->getIdentity(); ?>'  onclick="update('quan_trong', <?php echo $tin_tuc->getIdentity(); ?>,this)" checked />
					<?php else: ?>
						<input type="checkbox" id='tin_tuc_quan_trong_<?php echo $tin_tuc->getIdentity(); ?>'  onclick="update('quan_trong', <?php echo $tin_tuc->getIdentity(); ?>,this)" />
					<?php endif; ?>
				</div>
			</td>
			<td class="center">
				<div id='tin_tuc_content_noi_bat_<?php echo $tin_tuc->getIdentity(); ?>'>
					<?php if($tin_tuc->noi_bat): ?>
						<input type="checkbox" id='tin_tuc_noi_bat_<?php echo $tin_tuc->getIdentity(); ?>'  onclick="update('noi_bat', <?php echo $tin_tuc->getIdentity(); ?>,this)" checked />
					<?php else: ?>
						<input type="checkbox" id='tin_tuc_noi_bat_<?php echo $tin_tuc->getIdentity(); ?>'  onclick="update('noi_bat', <?php echo $tin_tuc->getIdentity(); ?>,this)" />
					<?php endif; ?>
				</div>
			</td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'tin-tuc','action' => 'sua','id' => $tin_tuc['id']),null,true)?>" title="Edit"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'tin-tuc','action' => 'xoa','id' => $tin_tuc['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->