<?php
	echo $this->doctype();
	$this->title = "Đơn vị";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách đơn vị</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_don_vi">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'don-vi','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_donvi" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th>Mã</th>
			<th>Tên</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'don-vi','action' => 'them'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $don_vi) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$don_vi['id'],null)?></td>
			<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'don-vi','action' => 'sua','id' => $don_vi['id']),null,true)?>"><?php echo $don_vi['ma']?></a></td>
			<td><?php echo $don_vi['ten']?></td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'don-vi','action' => 'sua','id' => $don_vi['id']),null,true)?>" title="Edit"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'don-vi','action' => 'xoa','id' => $don_vi['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->