<?php
	echo $this->doctype();
	$this->title = "Lịch học";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách lịch học</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_lich_hoc">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'lich-hoc','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_thongbao" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th class="tieu_de">Tiêu đề</th>
			<th class="center">Loại</th>
			<th class="center"><a href="javascript:void(0);" onclick="javascript:changeOrder('ngay_tao', 'DESC');">Ngày tạo</a></th>
			<th class="center">Trạng thái</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'lich-hoc','action' => 'them'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $lich_hoc) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$lich_hoc['id'],null)?></td>
			<td class="tieu_de"><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'lich-hoc','action' => 'sua','id' => $lich_hoc['id']),null,true)?>"><?php echo $lich_hoc['tieu_de']?></a></td>
			<td class="center"><?php echo $lich_hoc->getTenLoai()?></td>
			<td class="center"><?php echo date('d-m-Y', strtotime($lich_hoc['ngay_tao']))?></td>
			<td class="center">
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'lich-hoc','action' => 'cap-nhat-tt','id' => $lich_hoc['id'],'status' => $lich_hoc['trang_thai']))?>">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/trangthai_' . $lich_hoc['trang_thai'] . '.png'?>"> </a>
			</td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'lich-hoc','action' => 'sua','id' => $lich_hoc['id']),null,true)?>" title="Edit"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'lich-hoc','action' => 'xoa','id' => $lich_hoc['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->