<?php
	echo $this->doctype();
	$this->title = "Hộp thư";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách thư góp ý</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<?php echo $this->form;?>
<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_gop_y">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'hop-thu','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_hopthu" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th class="chu_de" style="width: 35%;">Chủ đề</th>
			<th class="center">Loại</th>
			<th class="center">Tình trạng</th>
			<th class="center">Người gởi</th>
			<th class="center">Ngày gởi</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>				
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $gop_y) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]', $gop_y->gop_y_id,null)?></td>
			<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hop-thu','action' => 'chi-tiet','id' => $gop_y->gop_y_id),null,true)?>"><?php echo Khcn_Api::_()->subPhrase($gop_y->ten, 200);?></a></td>
			<td class="center"><?php echo $gop_y->getLoai()->ten?></td>
			<td class="center"><?php echo $this->tinhTrangOptions[$gop_y->tinh_trang]?></td>
			<td class="center"><?php echo $gop_y->getNguoiDung()->ten_dang_nhap?></td>
			<td class="center"><?php echo date('d/m/Y', strtotime($gop_y->ngay_tao))?></td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hop-thu','action' => 'xoa','id' => $gop_y->gop_y_id),null,true)?>" title="Xóa" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->