<?php
	echo $this->doctype();
	$this->title = "Hình ảnh chuyên đề";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Hình ảnh chuyên đề: <a href="<?php echo $this->url(array('module' => 'admin','controller' => 'sinh-hoat-chuyen-de','action' => 'sua','id' => $this->sinh_hoat_chuyen_de->getIdentity()),null,true)?>" title="<?php echo $this->sinh_hoat_chuyen_de->getTitle()?>"><?php echo Khcn_Api::_()->default()->subPhrase($this->sinh_hoat_chuyen_de->getTitle(), 120);?></a></h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_hinh_anh">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'sinh-hoat-chuyen-de','action' => 'xoas-ha', 'id' => $this->sinh_hoat_chuyen_de->getIdentity()),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_hinhanh" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th>Hình</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'sinh-hoat-chuyen-de','action' => 'them-ha', 'id' => $this->sinh_hoat_chuyen_de->getIdentity()),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $hinh_anh) 
    	{
    ?>
    		<tr>
				<td><?php echo $this->formCheckbox('item[]',$hinh_anh->getIdentity(),null)?></td>
				<td class="hinh_anh"><img src="<?php echo $hinh_anh->getPhotoUrl()?>" /></td>
				<td>				
					<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'sinh-hoat-chuyen-de','action' => 'xoa-ha', 'id' => $this->sinh_hoat_chuyen_de->getIdentity(), 'hinh_anh_id' => $hinh_anh->getIdentity()),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
					<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
				</a></td>
			</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->