<?php
	echo $this->doctype();
	$this->title = "Sinh hoạt chuyên đề";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách Sinh hoạt chuyên đề</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<?php echo $this->form;?>
<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_sinh_hoat_chuyen_de">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'sinh-hoat-chuyen-de','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_hoithao" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th class="chu_de" style="width: 80%;">Chuyên đề</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'sinh-hoat-chuyen-de','action' => 'them'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $sinh_hoat_chuyen_de) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$sinh_hoat_chuyen_de->getIdentity(),null)?></td>
			<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'sinh-hoat-chuyen-de','action' => 'sua','id' => $sinh_hoat_chuyen_de->getIdentity()),null,true)?>" title="<?php echo $sinh_hoat_chuyen_de->getTitle()?>"><?php echo $sinh_hoat_chuyen_de->getTitle();?></a></td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'sinh-hoat-chuyen-de','action' => 'hinh-anh','id' => $sinh_hoat_chuyen_de->getIdentity()),null,true)?>" title="Hình Ảnh Chuyên Đề"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/add.png'?>" alt="Add"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'sinh-hoat-chuyen-de','action' => 'sua','id' => $sinh_hoat_chuyen_de->getIdentity()),null,true)?>" title="Sửa"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'sinh-hoat-chuyen-de','action' => 'xoa','id' => $sinh_hoat_chuyen_de->getIdentity()),null,true)?>" title="Xóa" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->