<?php
	$this->title = "Sinh hoạt chuyên đề";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box"><!-- Start Content Box -->

<div class="content-box-header">

<h3>Thêm Sinh hoạt chuyên đề</h3>

<div class="clear"></div>
</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1"><!-- This is the target div. id must match the href of this div's tab -->
<?php echo $this->form?>
<script type="text/javascript">
CKEDITOR.replace( 'noi_dung', {'skin' : 'v2','height' : '500px'} );
$(function() {
	$( "#thoi_gian" ).datepicker({
		showOn: "button",
		changeYear: true,
		changeMonth: true,
		buttonImage: "<?php echo $baseURL . '/images/calendar.gif'?>",
		buttonImageOnly: true,
		altFormat: 'yy-mm-dd',
		dateFormat: 'yy-mm-dd',
		yearRange : '2005:2030'
	});
});
</script>
</div>
<!-- End #tab1 -->
<!--<div class="tab-content" id="tab2"></div>-->
</div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->