<?php
	echo $this->doctype();
	$this->title = "Loại hồ sơ";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>
	Danh sách loại hồ sơ
	<?php if(!empty($this->parent_id)):?>
		<?php $parent = Khcn_Api::_()->getItem('default_loai_ho_so', $this->parent_id);?>
		<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-hs','action' => 'index', 'ma_loai' => $parent->parent_id))?>"><span style="color: red">: <?php echo $parent->getTitle();?></span></a>
	<?php endif;?>
</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_loai_bm">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-hs','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_hocvi" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th>Tên</th>
			<th>Ghi chú</th>
			<th>Thứ tự</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'loai-hs','action' => 'them', 'ma_loai' => $this->parent_id),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $loai_bm) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$loai_bm['id'],null)?></td>
			<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-hs','action' => 'sua','id' => $loai_bm['id']),null,true)?>"><?php echo $loai_bm['ten']?></a></td>
			<td><?php echo $loai_bm['ghi_chu']?></td>
			<td><?php echo $loai_bm['order']?></td>
			<td>
				<!--<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-hs','action' => 'index','ma_loai' => $loai_bm['id']),null,true)?>" title="Sub Category"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/add.png'?>" alt="Add"> </a>-->
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-hs','action' => 'sua','id' => $loai_bm['id'],'ma_loai' => $this->parent_id),null,true)?>" title="Edit"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-hs','action' => 'xoa','id' => $loai_bm['id'],'ma_loai' => $this->parent_id),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->