<?php
	echo $this->doctype();
	$this->title = "Import";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box">
<script type="text/javascript">
function kiem_tra(){
	if(document.getElementById('f3').ma_don_vi.value == 0)
	{
		alert('Bạn chưa chọn đơn vị.Vui lòng kiểm tra lại')	;
		return false;
	}
	return true;
}
</script>
<div class="content-box-header">

<h3>Import đề tài</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div id="import_dt">
<?php echo $this->form;?>
</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#xem_du_lieu").click(function(){
		var $form = $("#f3");
		$.ajax({ type: "POST", 
				 url: "<?php echo $this->url(array('module' => 'admin','controller' => 'import','action' => 'preview'))?>",
				 data: $form.serialize(),
				 success: function(responce) {
					 $('#data').replaceWith('');
				     // Insert list
				     $("#import").after(responce);
				 }
		});
	});
});
</script>

<!-- End #tab1 --></div>
<!-- End .content-box-content --></div>