<?php
	echo $this->doctype();
	$this->title = "Hội đồng nghiệm thu";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<script>
	var currentOrder = '<?php echo $this->filterValues['order'] ?>';
    var currentOrderDirection = '<?php echo $this->filterValues['direction'] ?>';
    var changeOrder = function(order, default_direction)
    {
		// Just change direction
		if( order == currentOrder ) {
			$('#direction').val( currentOrderDirection == 'ASC' ? 'DESC' : 'ASC' );
		} else {
			$('#order').val(order);
			$('#direction').val(default_direction);
		}
		$('#f3').submit();
    }
</script>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách hội đồng nghiệm thu</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<?php echo $this->form;?>
<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_hdnt">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'xoas-hdnt'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_hdnt" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th><a href="javascript:void(0);" onclick="javascript:changeOrder('ma', 'DESC');">Mã</a></th>
			<th><a href="javascript:void(0);" onclick="javascript:changeOrder('ngay_thanh_lap', 'DESC');">Ngày thành lập</a></th>
			<th style="width: 40%">Tên đề tài</th>
			<th class="center">Lĩnh vực</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'them-hdnt'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $hdnt) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$hdnt['id'],null)?></td>
			<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'sua-hdnt','id' => $hdnt['id']),null,true)?>"><?php echo $hdnt['ma']?></a></td>
			<td><?php echo $hdnt['ngay_thanh_lap']?></td>
			<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'de-tai','action' => 'sua','id' => $hdnt['id_de_tai']),null,true)?>"><?php echo $hdnt['ma_de_tai']?></a> - <?php echo $hdnt['ten_de_tai']?></td>
			<td class="center"><?php echo $hdnt['ten_linh_vuc']?></td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'sua-hdnt','id' => $hdnt['id']),null,true)?>" title="Edit"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'xoa-hdnt','id' => $hdnt['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->