<?php
	echo $this->doctype();
	$this->title = "Mail Thông báo";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách mail thông báo</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_mail_tb">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'xoas-mail-tb'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_mail_tb" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>			
			<th width="45%">Tiêu đề</th>
			<th class="center" width="15%">Gởi đến</th>			
			<th class="center" width="15%">Ngày gởi</th>
			<th class="center" width="15%">Loại</th>
			<th width="10%"></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm thông báo duyệt',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'tb-duyet'),null,true) . '"','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm thông báo nghiệm thu',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'td-nghiem-thu'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	$loais = Default_Model_Constraints::mail_tb_loai();
    	foreach ($this->paginator as $mail_tb) 
    	{
    		if($mail_tb['loai'] == 1){
    ?>
	    		<tr>
				<td><?php echo $this->formCheckbox('item[]',$mail_tb['id'],null)?></td>
				<td class="tieu_de"><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'sua-tb-duyet','id' => $mail_tb['id']),null,true)?>"><?php echo $mail_tb['tieu_de']?></a></td>
				<td class="center"><?php echo $mail_tb['noi_nhan']?></td>
				<td class="center"><?php echo $mail_tb['ngay_goi']?></td>
				<td class="center"><?php echo $loais[$mail_tb['loai']]?></td>
				<td>
					<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'sua-tb-duyet','id' => $mail_tb['id']),null,true)?>" title="Edit"> 
					<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
					<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'xoa-mail-tb','id' => $mail_tb['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
					<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
				</a></td>
				</tr>
    <?php
    		}else{
    ?>	
    			<tr>
				<td><?php echo $this->formCheckbox('item[]',$mail_tb['id'],null)?></td>
				<td class="tieu_de"><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'sua-tb-nt','id' => $mail_tb['id']),null,true)?>"><?php echo $mail_tb['tieu_de']?></a></td>
				<td class="center"><?php echo $mail_tb['noi_nhan']?></td>
				<td class="center"><?php echo $mail_tb['ngay_goi']?></td>
				<td class="center"><?php echo $loais[$mail_tb['loai']]?></td>
				<td>
					<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'sua-tb-nt','id' => $mail_tb['id']),null,true)?>" title="Edit"> 
					<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
					<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'xoa-mail-tb','id' => $mail_tb['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
					<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
				</a></td>
				</tr>
    <?php		
    		}
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->