<?php
	echo $this->doctype();
	$this->title = "Hội đồng nghiệm thu";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<script src="<?php echo $baseURL . '/../application/templates/admin/scripts/facebox.js'?>"></script>
<?php echo $this->render('don-vi/faceboxDV.phtml')?>
<?php echo $this->render('giang-vien/faceboxGV.phtml')?>
<?php echo $this->message()?>
<div class="content-box"><!-- Start Content Box -->

<div class="content-box-header">

<h3>Cập nhật hội đồng nghiệm thu</h3>
</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1"><!-- This is the target div. id must match the href of this div's tab -->
<?php echo $this->form?>
<script type="text/javascript">
    $(document).ready(function(  ){
    	var $id = $("#id").val();
    	$("#id-label").load("<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'selected-dt','hd' => 'hdnt'))?>",{id : $id});
    });
</script>
<script type="text/javascript">
$(document).ready(function(){ 
	$("#ma").blur(function(){
		var ma = $('#ma').val();
		var $form = $("form#f2");
		$.ajax({ type: "POST", 
				 url: "<?php echo $this->url(array('module' => 'admin','controller' => 'hoi-dong','action' => 'kiem-tra-id-ma-hdnt'))?>", 
				 data: $form.serialize(),
				 success: function(data){
					 $('#ajax').replaceWith('');
			         // if the result is TRUE write a message to the page
			         if (data == "YES") {
			           $('#ma').after('<span id="ajax" class="input-notification error png_bg">' +
			             'Mã hội đồng nghiệm thu đã tồn tại.</span>');
			         }else if(data == "NO"){
			        	$('#ma').after('<span id="ajax" class="input-notification success png_bg">' +
			            'Có thể sử dụng.</span>');
			         }else if (data == "ERROR") {
			            $('#f2 input[name=ma]').after('<span id="ajax" class="input-notification error png_bg">' +
			             'Mã không đúng định dạng.</span>');
			         }}
			});
	});
    
	$("#dsdt").click( 
        function() { 
            list();
        }
    );
		 
	$("#loc").click(
	    function() {
	        filter();
	    }
	);
});

function list() {
	var $form = $("form#f2");
	$.ajax(
	{
		 type: "POST",
		 url: "<?=$this->url(array('action' => 'list-dt','hd' => 'hdnt'));?>",
		 data: $form.serialize(),
		 success: function(responce) {
			 $('#danh_sach_dt').replaceWith('');
		     // Insert list
		     $("#btn_function").after(responce);
		 }
	}
	);
}

function filter() {
	var $form = $('form#f2');
	$.ajax(
	{
		 type: "POST",
		 url: "<?=$this->url(array('action' => 'filter-dt'));?>",
		 data: $form.serialize(),
		 success: function(responce) {
			 $('#danh_sach_dt').replaceWith('');
		     // Insert list
		     $("#btn_function").after(responce);
		 }
	}
	);
}

function change(dk,id)
{
	var ma = dk.value;
	$.ajax({
			 type: "POST",
			 url: "<?php echo $this->url(array('module' => 'admin','controller' => 'giang-vien','action' => 'load'))?>", 
			 data: {'id' : ma},
			 success: function(response){
				 $('#thanh_vien_' + id).empty().append(response);
		     }
		});	
}
</script>
<script>
$(function() {
	$( "#ngay_thanh_lap" ).datepicker({
		showOn: "button",
		changeYear: true,
		changeMonth: true,
		buttonImage: "<?php echo $baseURL . '/images/calendar.gif'?>",
		buttonImageOnly: true,
		altFormat: 'dd-mm-yy',
		dateFormat: 'dd-mm-yy',
		yearRange : '2005:2030'
	});
});
</script>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->