<?php
	echo $this->doctype();
	$this->title = "Thông báo nghiệm thu";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box"><!-- Start Content Box -->

<div class="content-box-header">

<h3>Thông báo nghiệm thu</h3>
</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1"><!-- This is the target div. id must match the href of this div's tab -->
<?php echo $this->form?>
<script type="text/javascript">
$(document).ready(function(){ 
	$("#nam").change(function(){
		change();		
	});
	$("#ma_don_vi").change(function(){
		change();		
	});
	
	CKEDITOR.replace( 'noi_dung', {'skin' : 'v2', 'toolbar' : [ 
		["Source"],
		["TextColor","BGColor","FontSize"],
		["Bold", "Italic", "Underline","-","Undo","Redo"],
		["NumberedList","BulletedList","-","Outdent","Indent"],
		["JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock"], 
		["SpecialChar"]
	]} );
});
function change(){
	var nam = $('#nam').val();
	var ma_don_vi = $('#ma_don_vi').val();
	$.ajax({
		 type: "POST",
		 url: "<?php echo $this->url(array('module' => 'admin','controller' => 'de-tai','action' => 'load'))?>", 
		 data: {'nam' : nam,'ma_don_vi' : ma_don_vi},
		 success: function(response){		
			 $('#ajax').replaceWith('');
			 var responses = response.split(",");
			 if(responses[0] == "NO"){
				 $('#nam').after('<span id="ajax" class="input-notification error png_bg">' +
	             'Không có dữ liệu.</span>');	
			 }		
			 $('#noi_nhan').empty().append(responses[1]);
	     }
	});
}
</script>
</div>

<!-- End #tab1 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->